export * from "./contracts";
export * from "./login";
export * from "./menu";
export * from "./migration-manifest";
export * as monitorCacheApi from "./monitor/cache";
export * as monitorJobApi from "./monitor/job";
export * as monitorJobLogApi from "./monitor/jobLog";
export * as monitorLoginInfoApi from "./monitor/logininfor";
export * as monitorOnlineApi from "./monitor/online";
export * as monitorOperationLogApi from "./monitor/operlog";
export * as monitorServerApi from "./monitor/server";
export * as systemConfigApi from "./system/config";
export * as systemDeptApi from "./system/dept";
export * as systemDictDataApi from "./system/dict/data";
export * as systemDictTypeApi from "./system/dict/type";
export * as systemMenuApi from "./system/menu";
export * as systemNoticeApi from "./system/notice";
export * as systemPostApi from "./system/post";
export * as systemRoleApi from "./system/role";
export * as systemUserApi from "./system/user";
export * as generatorApi from "./tool/gen";
export * as swaggerApi from "./tool/swagger";
